# Generated by Django 5.2 on 2026-07-30

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("catalogos", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Resolucion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("normal", "Normal"), ("reconocimiento_saberes", "Reconocimiento de saberes"), ("rectificacion", "Rectificación")], default="normal", max_length=32)),
                ("estado", models.CharField(choices=[("generada", "Generada"), ("en_proceso", "En proceso"), ("error", "Error")], default="en_proceso", max_length=32)),
                ("resolucion_nro", models.CharField(blank=True, max_length=100)),
                ("fecha", models.DateField()),
                ("batch_id", models.UUIDField(blank=True, db_index=True, default=None, null=True)),
                ("archivo_docx", models.FileField(blank=True, null=True, upload_to="resoluciones/docx/")),
                ("archivo_pdf", models.FileField(blank=True, null=True, upload_to="resoluciones/pdf/")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("alumno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resoluciones", to="catalogos.alumno")),
                ("tecnicatura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resoluciones", to="catalogos.tecnicatura")),
            ],
            options={"verbose_name": "resolución", "verbose_name_plural": "resoluciones", "ordering": ["-fecha", "-creado_en"]},
        ),
        migrations.CreateModel(
            name="ResolucionMateria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("equivalencia", models.TextField()),
                ("anio_cursado", models.PositiveSmallIntegerField()),
                ("institucion", models.CharField(max_length=200)),
                ("carrera_origen", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equivalencias", to="catalogos.carreraorigen")),
                ("materia", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equivalencias", to="catalogos.materia")),
                ("resolucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materias", to="resoluciones.resolucion")),
            ],
            options={"verbose_name": "materia de resolución", "verbose_name_plural": "materias de resolución"},
        ),
    ]
