# Generated by Django 5.2 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("dni", models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={"verbose_name": "alumno", "verbose_name_plural": "alumnos", "ordering": ["apellido", "nombre"]},
        ),
        migrations.CreateModel(
            name="CarreraOrigen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
            ],
            options={"verbose_name": "carrera de origen", "verbose_name_plural": "carreras de origen", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
            ],
            options={"verbose_name": "materia", "verbose_name_plural": "materias", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="Tecnicatura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("res_ministerial", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "tecnicatura", "verbose_name_plural": "tecnicaturas", "ordering": ["nombre"]},
        ),
    ]
