# Generated by Django 5.2 on 2026-08-13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoteCarga",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("archivo_original", models.CharField(max_length=255)),
                ("total_filas", models.PositiveIntegerField()),
                ("total_resoluciones", models.PositiveIntegerField(default=0)),
                ("errores", models.JSONField(blank=True, default=list)),
                ("estado", models.CharField(choices=[("pendiente", "Pendiente"), ("procesando", "Procesando"), ("completado", "Completado"), ("con_errores", "Con errores")], default="pendiente", max_length=20)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "lote de carga", "verbose_name_plural": "lotes de carga", "ordering": ["-creado_en"]},
        ),
    ]
